djangosite/ToDoApp/urls.py
from django.urls import path
from django.contrib.auth.views import login, logout

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('login', login, name='login'),
    path('logout', logout, {'next_page': 'login'}, name='logout'),
]

djangosite/djangosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ToDoApp/', include('ToDoApp.urls')),
]

djangosite/ToDoApp/models.py
from django.db import models


class ToDoList(models.Model):
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField('date created')


class ToDoTask(models.Model):
    todo_text = models.CharField(max_length=300)
    date_created = models.DateTimeField('date created')
    is_todo = models.BooleanField(default=False)
    is_inprogress = models.BooleanField(default=False)
    is_done = models.BooleanField(default=False)
    date_finished = models.DateTimeField(default=None, null=True, verbose_name='date finished')

    list_ref = models.ForeignKey(ToDoList, on_delete=models.DO_NOTHING)

djangosite/ToDoApp/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from .models import ToDoList


def index(request):
    if not request.user.is_authenticated:
        return HttpResponse("""Please <a href="login">login</a>...""")
    todo_lists = ToDoList.objects.all()

    context = {'todo_lists': todo_lists}
    return render(request, 'ToDoApp/index.html', context)

djangosite/ToDoApp/templates/ToDoApp/index.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
    <head>
        <meta charset="UTF-8">
        <title>ToDoApp</title>
        <link rel="stylesheet" type="text/css" href="{% static 'ToDoApp/bootstrap-3.3.7/css/bootstrap.min.css' %}"/>
        <script src="https://code.jquery.com/jquery-1.12.2.min.js" integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk=" crossorigin="anonymous"></script>
        <script src="{% static 'ToDoApp/bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
    </head>
    <body>
        <div class="panel panel-info" align="top">
            <div class="panel-body">
                <nav class="navbar navbar-default">
                  <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                      <a class="navbar-brand" href="#">Brand</a>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                      <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                        <li><a href="#">Link</a></li>
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                          </ul>
                        </li>
                      </ul>
                      <form class="navbar-form navbar-left">
                        <div class="form-group">
                          <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                      </form>
                      <ul class="nav navbar-nav navbar-right">
                          <li><a href="logout"><b>Logout</b></a></li>
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                          </ul>
                        </li>
                      </ul>
                    </div><!-- /.navbar-collapse -->
                  </div><!-- /.container-fluid -->
                </nav>
            </div>
        </div>

        <h1 align="center"><span class="label label-primary">ToDoApp's Home</span></h1>
        {% if todo_lists %}
            {% for todo_list in todo_lists %}
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title"><b>{{todo_list.name}}</b></h3>
                    </div>
                    <div class="panel-body">
                        <ul>
                            {% for todo_task in todo_list.todotask_set.all %}
                                <li>{{todo_task.todo_text}} --> {{todo_task.date_created}}</li>
                            {% endfor %}
                        </ul>
                        <form action="index" method="post">
                            {% csrf_token %}
                                <input type="text" name="task" id="todo_list{{forloop.counter}}" value="{{task_text}}" />
                            <input type="submit" class="btn btn-success" value="Add Task">
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No lists available. Please create some!</p>
        {% endif %}
    </body>
</html>